# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Qtk-QuickTk
version:      0.9
version_from: QuickTk.pm
installdirs:  site
requires:
    Text::TreeFile:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
